### DISCUSSION TITLE
Cannot commit file due to github actions failed tests

### DISCUSSION THREAD

**Discussion by annagabriel-hash** [avionschool/batch8-activities#18] [Q&A] [answered]
Project: Stock Transfer App

**To Reproduce**
1. Clone repo https://github.com/avionschool/rails-base-project
2. Run `bundle install`
4. Open _Gemfile_ and change `ruby '2.7.2'` to `ruby '2.7.3'`
5. Open _.tool-version_ and change `ruby '2.7.2'` to `ruby '2.7.3'`
6. Run `rails db:setup`
7. Open _.tool-version_ and change yarn version to `yarn 1.22.10`
8. Run `bundle install`
9. Add and commit _gemfile, gemlock and .tool version_ to repo
10. See error on github actions

**Screenshots**
![image](https://user-images.githubusercontent.com/79251819/129360885-200edba8-2585-44e2-b8b7-5a5137a603f4.png)

**Proposed Resolution**(c/o Sir Edwin)
1. Go to .rspec.yml
2. Change `ruby version to 2.7.3`
    Sample code
```
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.3
        bundler-cache: true
```
3. Add and commit files to github
